blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/0softwaredevelopment0/Discussions/discussions
    about: For general questions and conversations, please use GitHub Discussions.
  - name: Discord
    url: https://dsc.gg/0softwaredevelopment0
    about: Join our Discord server for real-time help and chat.
